[common info]
base_url = https://rahulshettyacademy.com/client


[pytest]
#to identify the tests folder, if we run tests from root then this helps to identify where the tests are
testpaths = tests

#command line argument to run tests - just type pytest in terminal and this will automatically adds to it
addopts = -v -s -n=auto --reruns 2 --headless=true --alluredir=reports/allure-results --clean-alluredir
#clean is for cleaning the reports folder before starting tests if any tests removed it will update in report